import type { ConfigResponse } from '../../shared/contracts/http.js';

export const GLITCH_CONFIG_KEYS = [
  'glitchFxEnabled',
  'glitchFxBaseColor',
  'glitchRenderer',
  'glitchScanlines',
  'glitchScanlineIntensity',
  'glitchScanlineSpacing',
  'glitchScanlineThickness',
  'glitchScanlineSpeed',
  'glitchPixelJitter',
  'glitchFlicker',
  'glitchFlickerSpeed',
  'glitchFlickerDepth',
  'glitchGlowStrength',
  'glitchBrightnessPulseEnabled',
  'glitchBrightnessPulseDim',
  'glitchBrightnessPulseBright',
  'glitchBrightnessPulseSpeed',
  'glitchScanBeamEnabled',
  'glitchScanBeamSpeed',
  'glitchScanBeamLineWidth',
  'glitchScanBeamBrightness',
  'glitchScanBeamGlowStrength',
  'glitchScanBeamJitter',
  'glitchScanBeamColor',
  'glitchChromaticEnabled',
  'glitchChromaticOffsetX',
  'glitchChromaticOffsetY',
  'glitchChromaticIntensity',
  'glitchChromaticAnimate',
  'glitchChromaticAnimateSpeed',
  'glitchSliceEnabled',
  'glitchSliceCount',
  'glitchSliceMaxOffset',
  'glitchSliceSpeed',
  'glitchSliceIntensity',
  'glitchSliceColorShift',
  'glitchSliceGapChance',
  'glitchSliceIntervalMs',
  'glitchSliceBurstDurationMs',
] as const satisfies readonly (keyof ConfigResponse)[];

export type GlitchConfigKey = (typeof GLITCH_CONFIG_KEYS)[number];

export const GLITCH_PRESETS: Record<string, Partial<ConfigResponse>> = {
  default: {
    glitchFxEnabled: true,
    glitchFxBaseColor: '#a855f7',
    glitchRenderer: 'auto',
    glitchScanlines: true,
    glitchScanlineIntensity: 0.41,
    glitchScanlineSpacing: 5,
    glitchScanlineThickness: 3,
    glitchScanlineSpeed: 26,
    glitchPixelJitter: 0,
    glitchFlicker: true,
    glitchFlickerSpeed: 11,
    glitchFlickerDepth: 0.02,
    glitchGlowStrength: 14,
    glitchBrightnessPulseEnabled: true,
    glitchBrightnessPulseDim: 0.88,
    glitchBrightnessPulseBright: 1,
    glitchBrightnessPulseSpeed: 3,
    glitchScanBeamEnabled: true,
    glitchScanBeamSpeed: 10,
    glitchScanBeamLineWidth: 7,
    glitchScanBeamBrightness: 0.65,
    glitchScanBeamGlowStrength: 26,
    glitchScanBeamJitter: 1,
    glitchScanBeamColor: '#a600ff',
    glitchChromaticEnabled: true,
    glitchChromaticOffsetX: 0,
    glitchChromaticOffsetY: 4.5,
    glitchChromaticIntensity: 0.65,
    glitchChromaticAnimate: true,
    glitchChromaticAnimateSpeed: 7,
    glitchSliceEnabled: true,
    glitchSliceCount: 24,
    glitchSliceMaxOffset: 5,
    glitchSliceSpeed: 28,
    glitchSliceIntensity: 0.53,
    glitchSliceColorShift: 0.03,
    glitchSliceGapChance: 0.07,
    glitchSliceIntervalMs: 18000,
    glitchSliceBurstDurationMs: 1800,
  },
  cyberpunk: {
    glitchFxEnabled: true,
    glitchFxBaseColor: '#00ffcc',
    glitchRenderer: 'auto',
    glitchScanlines: true,
    glitchScanlineIntensity: 0.55,
    glitchScanlineSpacing: 4,
    glitchScanlineThickness: 2,
    glitchScanlineSpeed: 30,
    glitchPixelJitter: 1.5,
    glitchFlicker: true,
    glitchFlickerSpeed: 14,
    glitchFlickerDepth: 0.04,
    glitchGlowStrength: 20,
    glitchBrightnessPulseEnabled: true,
    glitchBrightnessPulseDim: 0.88,
    glitchBrightnessPulseBright: 1,
    glitchBrightnessPulseSpeed: 3,
    glitchScanBeamEnabled: true,
    glitchScanBeamSpeed: 10,
    glitchScanBeamLineWidth: 7,
    glitchScanBeamBrightness: 0.65,
    glitchScanBeamGlowStrength: 26,
    glitchScanBeamJitter: 1,
    glitchScanBeamColor: '#a600ff',
    glitchChromaticEnabled: true,
    glitchChromaticOffsetX: 2,
    glitchChromaticOffsetY: 5,
    glitchChromaticIntensity: 0.8,
    glitchChromaticAnimate: true,
    glitchChromaticAnimateSpeed: 10,
    glitchSliceEnabled: true,
    glitchSliceCount: 32,
    glitchSliceMaxOffset: 10,
    glitchSliceSpeed: 35,
    glitchSliceIntensity: 0.7,
    glitchSliceColorShift: 0.06,
    glitchSliceGapChance: 0.1,
    glitchSliceIntervalMs: 8000,
    glitchSliceBurstDurationMs: 2400,
  },
  minimal: {
    glitchFxEnabled: true,
    glitchFxBaseColor: '#e0e0e0',
    glitchRenderer: 'auto',
    glitchScanlines: false,
    glitchScanlineIntensity: 0.1,
    glitchScanlineSpacing: 6,
    glitchScanlineThickness: 1,
    glitchScanlineSpeed: 10,
    glitchPixelJitter: 0,
    glitchFlicker: false,
    glitchFlickerSpeed: 5,
    glitchFlickerDepth: 0,
    glitchGlowStrength: 8,
    glitchBrightnessPulseEnabled: false,
    glitchBrightnessPulseDim: 0.95,
    glitchBrightnessPulseBright: 1,
    glitchBrightnessPulseSpeed: 2,
    glitchScanBeamEnabled: false,
    glitchScanBeamSpeed: 10,
    glitchScanBeamLineWidth: 7,
    glitchScanBeamBrightness: 0.3,
    glitchScanBeamGlowStrength: 10,
    glitchScanBeamJitter: 0,
    glitchScanBeamColor: '#ffffff',
    glitchChromaticEnabled: false,
    glitchChromaticOffsetX: 0,
    glitchChromaticOffsetY: 0,
    glitchChromaticIntensity: 0,
    glitchChromaticAnimate: false,
    glitchChromaticAnimateSpeed: 5,
    glitchSliceEnabled: false,
    glitchSliceCount: 10,
    glitchSliceMaxOffset: 2,
    glitchSliceSpeed: 20,
    glitchSliceIntensity: 0.2,
    glitchSliceColorShift: 0,
    glitchSliceGapChance: 0,
    glitchSliceIntervalMs: 30000,
    glitchSliceBurstDurationMs: 800,
  },
  warm: {
    glitchFxEnabled: true,
    glitchFxBaseColor: '#ff8844',
    glitchRenderer: 'auto',
    glitchScanlines: true,
    glitchScanlineIntensity: 0.41,
    glitchScanlineSpacing: 5,
    glitchScanlineThickness: 3,
    glitchScanlineSpeed: 26,
    glitchPixelJitter: 0,
    glitchFlicker: true,
    glitchFlickerSpeed: 11,
    glitchFlickerDepth: 0.02,
    glitchGlowStrength: 16,
    glitchBrightnessPulseEnabled: true,
    glitchBrightnessPulseDim: 0.85,
    glitchBrightnessPulseBright: 1,
    glitchBrightnessPulseSpeed: 2,
    glitchScanBeamEnabled: true,
    glitchScanBeamSpeed: 6,
    glitchScanBeamLineWidth: 10,
    glitchScanBeamBrightness: 0.5,
    glitchScanBeamGlowStrength: 20,
    glitchScanBeamJitter: 0.5,
    glitchScanBeamColor: '#ff6600',
    glitchChromaticEnabled: true,
    glitchChromaticOffsetX: 0,
    glitchChromaticOffsetY: 4.5,
    glitchChromaticIntensity: 0.65,
    glitchChromaticAnimate: true,
    glitchChromaticAnimateSpeed: 7,
    glitchSliceEnabled: true,
    glitchSliceCount: 24,
    glitchSliceMaxOffset: 5,
    glitchSliceSpeed: 28,
    glitchSliceIntensity: 0.53,
    glitchSliceColorShift: 0.03,
    glitchSliceGapChance: 0.07,
    glitchSliceIntervalMs: 18000,
    glitchSliceBurstDurationMs: 1800,
  },
};

export function pickGlitchConfig(config: ConfigResponse): Partial<ConfigResponse> {
  const patch = {} as Record<GlitchConfigKey, ConfigResponse[GlitchConfigKey]>;
  for (const key of GLITCH_CONFIG_KEYS) {
    patch[key] = config[key];
  }
  return patch satisfies Partial<ConfigResponse>;
}

export function sanitizeImportedGlitchConfig(value: unknown): Partial<ConfigResponse> {
  if (typeof value !== 'object' || value === null) {
    return {};
  }

  const input = value as Record<string, unknown>;
  const patch = {} as Record<GlitchConfigKey, ConfigResponse[GlitchConfigKey]>;
  for (const key of GLITCH_CONFIG_KEYS) {
    if (key in input) {
      patch[key] = input[key] as ConfigResponse[typeof key];
    }
  }
  return patch satisfies Partial<ConfigResponse>;
}
